import type { BreachRecord, Identity, PolicySet, Settings } from "./types";

const T0 = Date.parse("2026-08-26T08:00:00.000Z");
const daysAgo = (n: number) => new Date(T0 - n * 24 * 60 * 60 * 1000).toISOString();

function sid(rid: number): string {
  return `S-1-5-21-1847362910-3928471023-1102948576-${rid}`;
}

export const FOREST = {
  domain: "adlerwerk.local",
  netbios: "ADLERWERK",
  dcName: "DC01.adlerwerk.local",
  forest: "adlerwerk.local",
  functionalLevel: "Windows Server 2016",
};

export const DEFAULT_SETTINGS: Settings = {
  hibpApiKey: "",
  domain: FOREST.domain,
  dcName: FOREST.dcName,
  forest: FOREST.forest,
  filterEnabled: true,
  autoElevate: true,
  checkPwnedPasswords: true,
};

export const DEFAULT_POLICIES: PolicySet = {
  baseline: {
    minLength: 12,
    minClasses: 3,
    requireUpper: true,
    requireLower: true,
    requireDigit: true,
    requireSpecial: false,
    banUsername: true,
    banDisplayName: true,
    banPwnedPasswords: true,
    minUniqueChars: 8,
    maxAgeDays: 90,
    historyCount: 24,
    banKeyboardWalks: false,
    banRepeats: false,
    banCommonWords: false,
  },
  elevated: {
    minLength: 16,
    minClasses: 4,
    requireUpper: true,
    requireLower: true,
    requireDigit: true,
    requireSpecial: true,
    banUsername: true,
    banDisplayName: true,
    banPwnedPasswords: true,
    minUniqueChars: 12,
    maxAgeDays: 30,
    historyCount: 24,
    banKeyboardWalks: true,
    banRepeats: true,
    banCommonWords: true,
  },
};

const adobe = {
  name: "Adobe",
  domain: "adobe.com",
  breachDate: "2013-10-04",
  dataClasses: ["E-Mail", "Passwort", "Namen"],
};
const collection1 = {
  name: "Collection #1",
  domain: "",
  breachDate: "2019-01-07",
  dataClasses: ["E-Mail", "Passwort"],
};
const linkedin = {
  name: "LinkedIn",
  domain: "linkedin.com",
  breachDate: "2012-05-05",
  dataClasses: ["E-Mail", "Passwort"],
};
const dropbox = {
  name: "Dropbox",
  domain: "dropbox.com",
  breachDate: "2012-07-01",
  dataClasses: ["E-Mail", "Passwort"],
};
const canva = {
  name: "Canva",
  domain: "canva.com",
  breachDate: "2019-05-24",
  dataClasses: ["E-Mail", "Namen", "Passwort"],
};
const twitter = {
  name: "Twitter",
  domain: "twitter.com",
  breachDate: "2021-01-01",
  dataClasses: ["E-Mail", "Namen"],
};

export const SEED_IDENTITIES: Identity[] = [
  {
    id: "u-anna",
    sam: "anna.weber",
    upn: "anna.weber@adlerwerk.local",
    mail: "anna.weber@adlerwerk.de",
    displayName: "Anna Weber",
    givenName: "Anna",
    surname: "Weber",
    department: "Finanzwesen",
    title: "Leiterin Controlling",
    enabled: true,
    lastPasswordSet: daysAgo(74),
    hibpStatus: "pwned",
    breaches: [adobe, collection1, linkedin],
    lastHibpCheck: daysAgo(0),
    sid: sid(1104),
    ou: "OU=Finanzwesen,DC=adlerwerk,DC=local",
    knownPwned: true,
  },
  {
    id: "u-max",
    sam: "max.koenig",
    upn: "max.koenig@adlerwerk.local",
    mail: "max.koenig@adlerwerk.de",
    displayName: "Max König",
    givenName: "Max",
    surname: "König",
    department: "IT",
    title: "Systemadministrator",
    enabled: true,
    lastPasswordSet: daysAgo(18),
    hibpStatus: "clean",
    breaches: [],
    lastHibpCheck: daysAgo(0),
    sid: sid(1105),
    ou: "OU=IT,DC=adlerwerk,DC=local",
    knownPwned: false,
  },
  {
    id: "u-lena",
    sam: "lena.hofmann",
    upn: "lena.hofmann@adlerwerk.local",
    mail: "lena.hofmann@adlerwerk.de",
    displayName: "Lena Hofmann",
    givenName: "Lena",
    surname: "Hofmann",
    department: "Vertrieb",
    title: "Key Account",
    enabled: true,
    lastPasswordSet: daysAgo(102),
    hibpStatus: "pwned",
    breaches: [collection1, canva],
    lastHibpCheck: daysAgo(0),
    sid: sid(1106),
    ou: "OU=Vertrieb,DC=adlerwerk,DC=local",
    knownPwned: true,
  },
  {
    id: "u-klaus",
    sam: "klaus.becker",
    upn: "klaus.becker@adlerwerk.local",
    mail: "klaus.becker@adlerwerk.de",
    displayName: "Klaus Becker",
    givenName: "Klaus",
    surname: "Becker",
    department: "Produktion",
    title: "Meister Schicht A",
    enabled: true,
    lastPasswordSet: daysAgo(41),
    hibpStatus: "clean",
    breaches: [],
    lastHibpCheck: daysAgo(0),
    sid: sid(1107),
    ou: "OU=Produktion,DC=adlerwerk,DC=local",
    knownPwned: false,
  },
  {
    id: "u-julia",
    sam: "julia.brandt",
    upn: "julia.brandt@adlerwerk.local",
    mail: "julia.brandt@adlerwerk.de",
    displayName: "Julia Brandt",
    givenName: "Julia",
    surname: "Brandt",
    department: "Geschäftsführung",
    title: "Geschäftsführerin",
    enabled: true,
    lastPasswordSet: daysAgo(11),
    hibpStatus: "pwned",
    breaches: [dropbox, twitter, adobe],
    lastHibpCheck: daysAgo(0),
    sid: sid(1108),
    ou: "OU=Geschäftsführung,DC=adlerwerk,DC=local",
    knownPwned: true,
  },
  {
    id: "u-ralf",
    sam: "ralf.stein",
    upn: "ralf.stein@adlerwerk.local",
    mail: "ralf.stein@adlerwerk.de",
    displayName: "Ralf Stein",
    givenName: "Ralf",
    surname: "Stein",
    department: "Service",
    title: "Field Engineer",
    enabled: true,
    lastPasswordSet: daysAgo(55),
    hibpStatus: "clean",
    breaches: [],
    lastHibpCheck: daysAgo(0),
    sid: sid(1109),
    ou: "OU=Service,DC=adlerwerk,DC=local",
    knownPwned: false,
  },
  {
    id: "u-mira",
    sam: "mira.yilmaz",
    upn: "mira.yilmaz@adlerwerk.local",
    mail: "mira.yilmaz@adlerwerk.de",
    displayName: "Mira Yilmaz",
    givenName: "Mira",
    surname: "Yilmaz",
    department: "IT",
    title: "IAM-Ingenieurin",
    enabled: true,
    lastPasswordSet: daysAgo(7),
    hibpStatus: "clean",
    breaches: [],
    lastHibpCheck: daysAgo(0),
    sid: sid(1110),
    ou: "OU=IT,DC=adlerwerk,DC=local",
    knownPwned: false,
  },
  {
    id: "u-tobias",
    sam: "tobias.klein",
    upn: "tobias.klein@adlerwerk.local",
    mail: "tobias.klein@adlerwerk.de",
    displayName: "Tobias Klein",
    givenName: "Tobias",
    surname: "Klein",
    department: "Vertrieb",
    title: "Innenvertrieb",
    enabled: true,
    lastPasswordSet: daysAgo(210),
    hibpStatus: "pwned",
    breaches: [collection1],
    lastHibpCheck: daysAgo(0),
    sid: sid(1111),
    ou: "OU=Vertrieb,DC=adlerwerk,DC=local",
    knownPwned: true,
  },
  {
    id: "u-admin",
    sam: "adm.koenig",
    upn: "adm.koenig@adlerwerk.local",
    mail: "max.koenig@adlerwerk.de",
    displayName: "Max König (Admin)",
    givenName: "Max",
    surname: "König",
    department: "IT",
    title: "Domain-Admin",
    enabled: true,
    lastPasswordSet: daysAgo(29),
    hibpStatus: "watching",
    breaches: [],
    lastHibpCheck: daysAgo(0),
    sid: sid(512),
    ou: "OU=IT,DC=adlerwerk,DC=local",
    knownPwned: false,
  },
  {
    id: "u-sofia",
    sam: "sofia.neri",
    upn: "sofia.neri@adlerwerk.local",
    mail: "sofia.neri@adlerwerk.de",
    displayName: "Sofia Neri",
    givenName: "Sofia",
    surname: "Neri",
    department: "Personal",
    title: "HR Business Partner",
    enabled: true,
    lastPasswordSet: daysAgo(63),
    hibpStatus: "pwned",
    breaches: [canva, linkedin],
    lastHibpCheck: daysAgo(0),
    sid: sid(1112),
    ou: "OU=Personal,DC=adlerwerk,DC=local",
    knownPwned: true,
  },
  {
    id: "u-jan",
    sam: "jan.voigt",
    upn: "jan.voigt@adlerwerk.local",
    mail: "jan.voigt@adlerwerk.de",
    displayName: "Jan Voigt",
    givenName: "Jan",
    surname: "Voigt",
    department: "Produktion",
    title: "Qualitätsprüfer",
    enabled: false,
    lastPasswordSet: daysAgo(400),
    hibpStatus: "unknown",
    breaches: [],
    lastHibpCheck: null,
    sid: sid(1113),
    ou: "OU=Produktion,DC=adlerwerk,DC=local",
    knownPwned: false,
  },
  {
    id: "u-emma",
    sam: "emma.scholz",
    upn: "emma.scholz@adlerwerk.local",
    mail: "emma.scholz@adlerwerk.de",
    displayName: "Emma Scholz",
    givenName: "Emma",
    surname: "Scholz",
    department: "Service",
    title: "Disponentin",
    enabled: true,
    lastPasswordSet: daysAgo(22),
    hibpStatus: "clean",
    breaches: [],
    lastHibpCheck: daysAgo(0),
    sid: sid(1114),
    ou: "OU=Service,DC=adlerwerk,DC=local",
    knownPwned: false,
  },
];

/** Names/emails that the local HIBP cache treats as pwned (demo + common dumps). */
export const LOCAL_PWNED_NAMES = new Set(
  [
    "test@test.com",
    "test@example.com",
    "admin",
    "administrator",
    "root",
    "guest",
    "info",
    "webmaster",
    "anna.weber",
    "anna.weber@adlerwerk.de",
    "lena.hofmann",
    "lena.hofmann@adlerwerk.de",
    "julia.brandt",
    "julia.brandt@adlerwerk.de",
    "tobias.klein",
    "tobias.klein@adlerwerk.de",
    "sofia.neri",
    "sofia.neri@adlerwerk.de",
    "john@doe.com",
    "user@gmail.com",
  ].map((s) => s.toLowerCase()),
);

export const LOCAL_BREACH_FALLBACK: BreachRecord[] = [collection1, adobe];
